package entities;

public enum ErrorEnum {
    DEFAULT,
    INVALID_COMMAND,
    INVALID_FORMAT,
    INVALID_PARAMETERS,
    NO_PARKING_FLOOR,
    PARKING_FLOOR_PRESENT,
    PARKING_FULL,
    NO_VEHICLE_FOUND,
    VEHICLE_ALREADY_PRESENT

}
